from numpy import random

MIN_PUISSANCE_BATTERIE, MAX_PUISSANCE_BATTERIE = -60, 60
MIN_PUISSANCE_HYDROGENE, MAX_PUISSANCE_HYDROGENE = 0, 60
SIZE_POPULATION = 25
N_GENERATIONS = 10

PDs = [random.randint(0, 70) for _ in range(100)]